# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 007bf33a92be213e9303ca105ccdefeca907dc5f68bf09e84bb652a4ed4666369fd2d35500769a2b3753eaa87608453b6a4d78d2c47ea8ab3445486f33d29551

test:
  secret_key_base: 0ac0255261577f12a8b0b58c9fd56564b7fec9b2e19591ba3b89cca9367df58a5a6e5629712e09221956e048af33b1086fed2f402b1e300c2e68430a9e61d3f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
